### ISSUE TITLE
Bump up base bound

### ISSUE THREAD

**Issue by FranklinChen** [wei2912/counter#1]
The base bound can be raised to support GHC 7.10.

**Comment by wei2912** [comment]
Thanks, updated in https://github.com/wei2912/counter/commit/289bf51822ae79b067a98a3ae0cbb1202fee402b and https://github.com/wei2912/counter/commit/bd2205c1861fed3ed35556ab26a9cfc37ffa013b.

Just curious, how did you find this library?

**Comment by FranklinChen** [comment]
I was just searching the Web to see if someone had already written a Haskell equivalent of Python's useful `Counter` class :-).

**Comment by wei2912** [comment]
Ah, I see. That's what inspired me to write this library too. :P
